version: 0.2         

phases:
  install:
      runtime-versions:
          node: 10.x
  build:
    commands:
      - npm install
      - npm run test
      
artifacts:
  files:
    - index.js
    - package.json
    - node_modules


